import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { z } from 'zod';
import { CapabilityToolAdapter } from '../CapabilityToolAdapter';
import { CapabilityExecutionService } from '../../../core/capabilities/CapabilityExecutionService';
import { CapabilityConfirmationService } from '../../../core/capabilities/CapabilityConfirmationService';
import { ServerCapabilityRegistry } from '../../../core/capabilities/serverCapabilityRegistry';
import { CapabilityToolNameRegistry } from '../../../core/capabilities/capabilityToolNameRegistry';
import { AuditService } from '../../../core/audit/auditService';
import { storage } from '../../../infrastructure/storage';

const user:any={id:'owner',email:'o@test',name:'Owner',roles:['owner'],permissions:[]};
const context:any={user,appContext:{user,availableCapabilities:[]},confirmed:false};
const cap=(handler=vi.fn(async()=>({ok:true})))=>({id:'test.hitl',moduleId:'system',description:'hitl',inputSchema:z.object({value:z.string()}).strict(),outputSchema:z.object({ok:z.literal(true)}).strict(),risk:'high',sideEffect:'mutation',confirmationPolicy:'required',permissions:[],execute:handler} as any);
function executor(tool:any){ if(typeof tool.runAsync==='function') return (args:any,ctx:any)=>tool.runAsync({args,toolContext:ctx}); const fn=tool.execute??tool.func??tool._execute??tool.config?.execute; return fn.bind(tool); }

describe('GĐ3 Lượt 4 HITL tool resume hardening',()=>{
 beforeEach(()=>{ServerCapabilityRegistry.reset();CapabilityToolNameRegistry.reset();vi.spyOn(AuditService,'log').mockResolvedValue({id:'a'} as any);vi.spyOn(AuditService,'update').mockResolvedValue();vi.spyOn(storage,'refreshModuleSettings').mockResolvedValue();});
 afterEach(()=>{vi.restoreAllMocks();ServerCapabilityRegistry.reset();CapabilityToolNameRegistry.reset();});
 it('persists original session/function identity when confirmation is prepared',async()=>{const c=cap();ServerCapabilityRegistry.register(c);const prep=vi.spyOn(CapabilityConfirmationService,'prepare').mockResolvedValue({confirmationId:'confirm-1',expiresAt:new Date(Date.now()+1000).toISOString()});const tool=CapabilityToolAdapter.createTool(c,context,{sessionId:'session-12345678'});await executor(tool)({value:'X'},{functionCallId:'call-12345678',requestConfirmation:vi.fn()});expect(prep).toHaveBeenCalledWith(expect.objectContaining({userId:'owner',capabilityId:'test.hitl',executionContext:expect.objectContaining({source:'agent',sessionId:'session-12345678',toolCallId:'call-12345678',logicalExecutionId:'agent:session-12345678:call-12345678'})}));});
 it('approved execution stays on CapabilityExecutionService and never directly invokes handler from adapter',async()=>{const handler=vi.fn(async()=>({ok:true}));const c=cap(handler);ServerCapabilityRegistry.register(c);const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:true,data:{ok:true}} as any);const tool=CapabilityToolAdapter.createTool(c,context,{sessionId:'session-12345678'});await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(gateway).toHaveBeenCalledWith('test.hitl',{value:'X'},expect.anything(),expect.objectContaining({sessionId:'session-12345678',toolCallId:'call-12345678',confirmationId:'confirm-1'}));expect(handler).not.toHaveBeenCalled();});
 it('rejection terminally consumes the original confirmation and never executes capability',async()=>{const c=cap();ServerCapabilityRegistry.register(c);const reject=vi.spyOn(CapabilityConfirmationService,'reject').mockResolvedValue({ok:true,confirmationId:'confirm-1'} as any);const gateway=vi.spyOn(CapabilityExecutionService,'execute');const tool=CapabilityToolAdapter.createTool(c,context,{sessionId:'session-12345678'});const result=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:false,payload:{confirmationId:'confirm-1'}}});expect(result).toMatchObject({errorCode:'CONFIRMATION_REJECTED'});expect(reject).toHaveBeenCalledWith(expect.objectContaining({confirmationId:'confirm-1',sessionId:'session-12345678',toolCallId:'call-12345678'}));expect(gateway).not.toHaveBeenCalled();});
 it('registers cancellation of a persisted pending challenge against the same identity',async()=>{const c=cap();ServerCapabilityRegistry.register(c);vi.spyOn(CapabilityConfirmationService,'prepare').mockResolvedValue({confirmationId:'confirm-1',expiresAt:new Date(Date.now()+1000).toISOString()});const cancel=vi.spyOn(CapabilityConfirmationService,'cancel').mockResolvedValue({ok:true,confirmationId:'confirm-1'} as any);const controller=new AbortController();const tool=CapabilityToolAdapter.createTool(c,context,{sessionId:'session-12345678',abortSignal:controller.signal});await executor(tool)({value:'X'},{functionCallId:'call-12345678',requestConfirmation:vi.fn()});controller.abort();await Promise.resolve();expect(cancel).toHaveBeenCalledWith(expect.objectContaining({confirmationId:'confirm-1',sessionId:'session-12345678',toolCallId:'call-12345678'}));});
 it('preserves temporary-mode marker only in short-lived confirmation safety context',async()=>{const c=cap();ServerCapabilityRegistry.register(c);const prep=vi.spyOn(CapabilityConfirmationService,'prepare').mockResolvedValue({confirmationId:'confirm-1',expiresAt:new Date(Date.now()+1000).toISOString()});const tool=CapabilityToolAdapter.createTool(c,context,{sessionId:'session-temp-123',temporaryMode:true});await executor(tool)({value:'X'},{functionCallId:'call-temp-123',requestConfirmation:vi.fn()});expect(prep).toHaveBeenCalledWith(expect.objectContaining({executionContext:expect.objectContaining({temporaryMode:true})}));});
});

describe('GĐ3 Lượt 4 approval/reload security behavior',()=>{
 beforeEach(()=>{ServerCapabilityRegistry.reset();CapabilityToolNameRegistry.reset();vi.spyOn(AuditService,'log').mockResolvedValue({id:'a'} as any);vi.spyOn(AuditService,'update').mockResolvedValue();vi.spyOn(storage,'refreshModuleSettings').mockResolvedValue();});
 afterEach(()=>{vi.restoreAllMocks();ServerCapabilityRegistry.reset();CapabilityToolNameRegistry.reset();});
 const setup=()=>{const c=cap();ServerCapabilityRegistry.register(c);return {c,tool:CapabilityToolAdapter.createTool(c,context,{sessionId:'session-12345678'})};};
 it('does not accept approval without the original confirmation identity',async()=>{const {tool}=setup();const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,requiresConfirmation:true,errorCode:'CONFIRMATION_REQUIRED',confirmationId:'confirm-new'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{}}});expect(r).toMatchObject({success:false,requiresConfirmation:true});expect(gateway).toHaveBeenCalledTimes(1);});
 it('forwards exact original args on approval rather than payload args',async()=>{const {tool}=setup();const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:true,data:{ok:true}} as any);await executor(tool)({value:'ORIGINAL'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1',value:'FORGED'}}});expect(gateway).toHaveBeenCalledWith('test.hitl',{value:'ORIGINAL'},expect.anything(),expect.anything());});
 it('does not take capability identity from confirmation payload',async()=>{const {tool}=setup();const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:true,data:{ok:true}} as any);await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1',capabilityId:'forged.cap'}}});expect(gateway.mock.calls[0][0]).toBe('test.hitl');});
 it('keeps original functionCallId after reload-style approval invocation',async()=>{const {tool}=setup();const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:true,data:{ok:true}} as any);await executor(tool)({value:'X'},{functionCallId:'call-original-123',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(gateway.mock.calls[0][3]).toMatchObject({sessionId:'session-12345678',toolCallId:'call-original-123'});});
 it('surfaces confirmation replay as a safe tool failure',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,errorCode:'CONFIRMATION_REPLAY',error:'internal'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(r).toMatchObject({errorCode:'CONFIRMATION_REPLAY',error:'Confirmation is no longer valid.'});});
 it('surfaces stale execution binding mismatch without internal details',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,errorCode:'CONFIRMATION_EXECUTION_MISMATCH',error:'sensitive'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-stale-123',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(r).toEqual(expect.objectContaining({errorCode:'CONFIRMATION_EXECUTION_MISMATCH',error:'Confirmation belongs to another tool execution.'}));expect(JSON.stringify(r)).not.toContain('sensitive');});
 it('surfaces cancellation as a terminal safe confirmation failure',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,errorCode:'CONFIRMATION_CANCELLED',error:'internal'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(r).toMatchObject({errorCode:'CONFIRMATION_CANCELLED'});});
 it('rechecks canonical gateway on approval instead of treating approval as success',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,errorCode:'CAPABILITY_DISABLED',error:'disabled'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(r).toMatchObject({success:false,errorCode:'CAPABILITY_DISABLED'});});
 it('rechecks permission through canonical gateway on approval',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,errorCode:'PERMISSION_DENIED',error:'denied'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(r).toMatchObject({success:false,errorCode:'PERMISSION_DENIED'});});
 it('does not expose raw approval execution exceptions',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,errorCode:'EXECUTION_ERROR',error:'credential=secret'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(r.error).toBe('Tool execution failed.');expect(JSON.stringify(r)).not.toContain('secret');});
 it('does not treat rejected approval as successful business result',async()=>{const {tool}=setup();vi.spyOn(CapabilityConfirmationService,'reject').mockResolvedValue({ok:true,confirmationId:'confirm-1'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:false,payload:{confirmationId:'confirm-1'}}});expect(r).toMatchObject({success:false,errorCode:'CONFIRMATION_REJECTED'});});
 it('fails rejection closed when terminal consume detects replay',async()=>{const {tool}=setup();vi.spyOn(CapabilityConfirmationService,'reject').mockResolvedValue({ok:false,confirmationId:'confirm-1',errorCode:'CONFIRMATION_REPLAY',errorSummary:'used'} as any);const r=await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:false,payload:{confirmationId:'confirm-1'}}});expect(r).toMatchObject({success:false,errorCode:'CONFIRMATION_REPLAY'});});
 it('keeps confirmation challenge payload bounded to identifiers and policy metadata',async()=>{const {tool}=setup();vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:false,requiresConfirmation:true,errorCode:'CONFIRMATION_REQUIRED',confirmationId:'confirm-1',confirmationExpiresAt:'2030-01-01T00:00:00.000Z'} as any);const requestConfirmation=vi.fn();await executor(tool)({value:'SECRET_INPUT'},{functionCallId:'call-12345678',requestConfirmation});const payload=requestConfirmation.mock.calls[0][0].payload;expect(payload).toEqual({capabilityId:'test.hitl',risk:'high',confirmationId:'confirm-1',expiresAt:'2030-01-01T00:00:00.000Z'});expect(JSON.stringify(payload)).not.toContain('SECRET_INPUT');});
 it('uses server-owned session even if model args contain a forged session field',async()=>{const c={...cap(),inputSchema:z.object({value:z.string(),sessionId:z.string().optional()}).strict()};ServerCapabilityRegistry.register(c as any);const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:true,data:{ok:true}} as any);const tool=CapabilityToolAdapter.createTool(c as any,context,{sessionId:'trusted-session'});await executor(tool)({value:'X',sessionId:'forged'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1'}}});expect(gateway.mock.calls[0][3]).toMatchObject({sessionId:'trusted-session'});});
 it('keeps approval execution source server-owned as agent',async()=>{const {tool}=setup();const gateway=vi.spyOn(CapabilityExecutionService,'execute').mockResolvedValue({success:true,data:{ok:true}} as any);await executor(tool)({value:'X'},{functionCallId:'call-12345678',toolConfirmation:{confirmed:true,payload:{confirmationId:'confirm-1',source:'rest'}}});expect(gateway.mock.calls[0][3]).toMatchObject({source:'agent'});});
});
